[build]
  command = "npm run build"
  publish = ".next"
  node_version = "20"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY,SUPABASE_SERVICE_ROLE_KEY,NEXT_PUBLIC_DOMAIN,NEXT_PUBLIC_VAPID_PUBLIC_KEY,OPENAI_API_KEY,GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET,META_APP_ID,META_APP_SECRET,EVOLUTION_API_URL,EVOLUTION_API_KEY,VAPID_PRIVATE_KEY,VAPID_CONTACT"
  NEXT_PUBLIC_DOMAIN = "https://autonexabrasil.com.br"
  NEXT_PUBLIC_VAPID_PUBLIC_KEY = "BKnYZNV3UE5WwsGa11nQLjeysJLCL2bDxR53aqjoLBQxjfr1kT3fBRDAFdA4rdlZ5WFnE3ng12u2dV97TEC1i9Q"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"